name: 'Template Populator Action'
description: 'Dynamically populates a template with data'
inputs:
  data-url:
    description: 'Data to populate the template with.'
    required: true
    default: 'resume.json'
  template-url: 
    description: 'Template for the data'
    required: true
    default: 'template.tex'
  variable-tags: 
    description: 'A JSON string representing the start and end tags. See action-e2e-test.yml for an example'
    required: false
  output-filename: 
    description: 'Name of the output file'
    required: true
    default: 'resume.tex'
outputs:
  populated-template:
    description: 'The template with the data filled in'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - data-url=${{ inputs.data-url }}
    - template-url=${{ inputs.template-url }}
    - variable-tags=${{ inputs.variable-tags }}
    - output-filename=${{ inputs.output-filename }}
