on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: A job to run the action and deploy it's output file to the sample s3 bucket
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Run Action
        uses: ./ 
        with: 
          template-url: https://gist.githubusercontent.com/joshmsamuels/951453f0aade3a132f6c8cbd91fd8a52/raw/56d6e6180e67cb8445a6e790809a4beb618c1640/populate-template-action-sample-template.tex
          data-url: https://gist.githubusercontent.com/joshmsamuels/96e1424acbe7e935493456c8d7b41ed1/raw/b80a57f73a4f5816a1b374170972740cccb96d39/populate-template-action-sample-data.json
          variable-tags: "{\"start\": \"<<\", \"end\": \">>\"}"
          output-filename: sample-file.pdf
      - name: Deploy
        run: aws s3 cp ./sample-file.pdf s3://joshmsamuels.populate-template-action.test-bucket
