on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: A job to run the action and deploy it's output file to the sample s3 bucket
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Run Action
        uses: ./ 
        with: 
          template-url: https://raw.githubusercontent.com/joshmsamuels/my-template/main/resume.tex
          data-url: https://gist.githubusercontent.com/joshmsamuels/96e1424acbe7e935493456c8d7b41ed1/raw/b80a57f73a4f5816a1b374170972740cccb96d39/populate-template-action-sample-data.json
          variable-tags: '{"start": "<<", "end": ">>"}'
          font-asset-urls: '["https://raw.githubusercontent.com/joshmsamuels/my-template/main/fonts/FontAwesome.ttf", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/fonts/Roboto-Bold.ttf", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/fonts/Roboto-BoldItalic.ttf", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/fonts/Roboto-Italic.ttf", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/fonts/FontAwesome.ttf"]'
          other-asset-urls: '["https://raw.githubusercontent.com/joshmsamuels/my-template/main/awesome-cv.cls", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/inputs/skills.tex", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/inputs/projects.tex", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/inputs/experience.tex", "https://raw.githubusercontent.com/joshmsamuels/my-template/main/inputs/education.tex"]'
          output-filename: sample-file.pdf
      - name: Deploy
        run: aws s3 cp ./sample-file.pdf s3://joshmsamuels.populate-template-action.test-bucket
